In [1]:
pwd


'C:\\Users\\NITHISH PATEL'

In [1]:
def leapyear(x):
    if x%4 == 0:
        print("1")
    elif x%400 == 0:
        print("1")
    else:
        print("0")


In [2]:
leapyear(2023)

0


In [3]:
import numpy as np

In [4]:
lst=[1,2,3,4]

In [5]:
n=np.array(lst)

In [6]:
type(n)

numpy.ndarray

In [35]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
ur_matrix=[[2,3,4],[4,5,6],[5,6,7]]

In [36]:
a=np.my_matrix[[1,2,3],[4,5,6],[7,8,9]]
b=np.ur_matrix[[2,3,4],[4,5,6],[5,6,7]]

AttributeError: module 'numpy' has no attribute 'my_matrix'

In [32]:
my_matrix+ur_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [2, 3, 4], [4, 5, 6], [5, 6, 7]]

In [23]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 3, 4],
       [4, 5, 6],
       [5, 6, 7]])

In [17]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [24]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [25]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.random.rand(4)

array([0.68835304, 0.88876944, 0.48332808, 0.01628738])

In [28]:
np.random.randint(1,100,5)

array([30,  5, 18, 92, 83])

In [30]:
ranarr= np.random.randint(1,100,10)

In [31]:
ranarr

array([36, 38, 38, 81, 54, 24, 89, 83, 99, 87])